Feat/config tailwind
ViktorShevchenko/online-chat pull request #2
Opened 2023-05-07 17:07 UTC by ViktorShevchenko

configured tailwind.css.

2023-05-07 17:30 UTC, Security2431 requested changes
Looks good, left some comments

2023-05-07 17:30 UTC, Security2431 commented on components/views/Demo/Demo.tsx
> +    console.log("count: ", count);
Please, get rid of `console.log`

2023-05-07 17:30 UTC, Security2431 commented on components/views/Demo/Demo.tsx
> +  }, [count]);
NIT: Testing multi lines review

2023-05-07 17:30 UTC, Security2431 commented on components/views/Demo/Demo.tsx
> +  const [count, setCount] = useState<number>(0);
Types for primitives are optional

```suggestion
  const [count, setCount] = useState(0);
```

2023-05-07 17:30 UTC, Security2431 commented on package.json
> +    "sass": "^1.62.1"
```suggestion
    "sass": "1.62.1"
```

2023-05-07 17:30 UTC, Security2431 commented on package.json
> +    "classnames": "^2.3.2",
```suggestion
    "classnames": "2.3.2",
```

2023-05-07 17:30 UTC, Security2431 commented on pages/index.tsx
> +const inter = Inter({ subsets: ["latin"] });
We've already added fonts in `_app.tsx`. This line is never used
```suggestion
const inter = Inter({ subsets: ["latin"] });
```

2023-05-07 17:30 UTC, Security2431 commented on pages/index.tsx
> +import { Inter } from "next/font/google";
pls, delete one. We've already imported fonts in `_app.tsx`

2023-05-07 17:30 UTC, Security2431 commented on styles/globals.scss
> +// }
Please, delete ones

2023-05-07 17:30 UTC, Security2431 commented on components/shared/Icon/Icon.module.scss
> +    speak: never;
Why do we use this line here?

2023-05-08 11:12 UTC, ViktorShevchenko commented on components/views/Demo/Demo.tsx
> +    console.log("count: ", count);
removed console.log

2023-05-08 11:17 UTC, ViktorShevchenko commented on components/views/Demo/Demo.tsx
> +  const [count, setCount] = useState<number>(0);
removed optional <number>

2023-05-08 11:20 UTC, ViktorShevchenko commented on package.json
> +    "sass": "^1.62.1"
inserted the proposed "devDependencies" into package.json and removed the caret symbol before the version nuber

2023-05-08 11:23 UTC, ViktorShevchenko commented on package.json
> +    "classnames": "^2.3.2",
inserted the "classnames" into package.json and removed the caret symbol before the version number

2023-05-08 11:24 UTC, ViktorShevchenko commented on package.json
> +    "classnames": "^2.3.2",
inserted the "classnames" into package.json and removed the caret symbol before the version number

2023-05-08 11:24 UTC, ViktorShevchenko commented on package.json
> +    "classnames": "^2.3.2",
inserted the "classnames" into package.json and removed the caret symbol before the version number

2023-05-08 11:25 UTC, ViktorShevchenko commented on pages/index.tsx
> +const inter = Inter({ subsets: ["latin"] });
removed const inter

2023-05-08 11:25 UTC, EdPrys commented on components/views/Demo/Demo.tsx
> +    console.log("count: ", count);
done

2023-05-08 11:36 UTC, ViktorShevchenko commented on pages/index.tsx
> +import { Inter } from "next/font/google";
deleted "import React from 'react';"

2023-05-08 11:39 UTC, ViktorShevchenko commented on styles/globals.scss
> +// }
file 'styles/globals.scss' not found

2023-05-08 11:42 UTC, ViktorShevchenko commented on components/shared/Icon/Icon.module.scss
> +    speak: never;
the file not found

2023-05-08 11:44 UTC, merged